// The fire a burning body is drawn with. Three things are checked here, and the middle one is the
// point of the file: not *which* effect is named, but whether an effect named for a body could be
// seen on one at all. That rule is the particle engine's own arithmetic, and an earlier cut of this
// wave picked a stand-in that failed both halves of it while every string-shaped check passed.
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { EXTRA_EFFECTS, extraEffect, extraEffectsStatus, missingExtraEffects, wornOnABody } from '../weapons.mjs';
import { FIRE_EFFECT, fireLookLine, pickFireLook } from '../../../src/player/fireLook.ts';

let checks = 0;
const ok = (cond: boolean, what: string) => {
  assert.ok(cond, what);
  checks++;
  console.log(`ok   ${what}`);
};

type Emitter = { generation?: string; localSpace?: boolean; oneShot?: boolean };
/** An effect file shaped as the converter writes one: groups of emitters, and nothing else read. */
const effectOf = (...emitters: Emitter[]) => ({ groups: [{ emitters }] });
/** The three emitters of the client's own burn, as it converts: rate-generated and local space. */
const burnShaped = effectOf(
  { generation: 'rate', localSpace: true, oneShot: false },
  { generation: 'rate', localSpace: true, oneShot: false },
  { generation: 'rate', localSpace: true, oneShot: false },
);
/** The three of the fireball the flame thrower's weapon row fires: distance-generated, world space. */
const fireballShaped = effectOf(
  { generation: 'distance', localSpace: false, oneShot: false },
  { generation: 'distance', localSpace: false, oneShot: false },
  { generation: 'distance', localSpace: false, oneShot: false },
);

// --- can it be worn by a body? -----------------------------------------------------------------
// Both halves of the rule, each failed on its own, then together, then the shapes that matter.
ok(wornOnABody(burnShaped).ok, "an effect shaped like the client's own burn can be worn by a body");
ok(!wornOnABody(fireballShaped).ok, 'an effect shaped like the fireball cannot');
ok(/standing still/.test(wornOnABody(fireballShaped).why), 'and the reason given is the one that bites first: nothing is drawn on a body at rest');

const stillButTrailing = effectOf({ generation: 'rate', localSpace: false });
ok(!wornOnABody(stillButTrailing).ok && /local space/.test(wornOnABody(stillButTrailing).why), 'a rate-generated effect that is not local space is refused: its flames stay where the body was');
const ridingButBlank = effectOf({ generation: 'distance', localSpace: true });
ok(!wornOnABody(ridingButBlank).ok && /standing still/.test(wornOnABody(ridingButBlank).why), 'a local-space effect generated by distance is refused: it rides the body and draws nothing');

// It is *every* emitter, not any: one bad emitter among good ones fails the effect, because that
// emitter is simply missing from what the body wears.
ok(!wornOnABody(effectOf({ generation: 'rate', localSpace: true }, { generation: 'distance', localSpace: true })).ok, 'one distance-generated emitter among rate-generated ones fails the whole effect');
ok(!wornOnABody(effectOf({ generation: 'rate', localSpace: true }, { generation: 'rate', localSpace: false })).ok, 'one world-space emitter among local ones fails the whole effect');
ok(/emitter 1 of 2/.test(wornOnABody(effectOf({ generation: 'rate', localSpace: true }, { generation: 'rate', localSpace: false })).why), 'and the reason names which emitter is at fault');

// A one-shot emitter bursts on its own: the engine's one-shot branch never reads the generation, so
// such an emitter draws on a body at rest whatever its generation says.
ok(wornOnABody(effectOf({ generation: 'distance', localSpace: true, oneShot: true })).ok, 'a one-shot emitter is judged on riding the body alone, since it bursts without moving');
ok(!wornOnABody(effectOf({ generation: 'rate', localSpace: true }, {})).ok, 'an emitter with neither property set is refused rather than assumed');
ok(!wornOnABody({ groups: [] }).ok && !wornOnABody(undefined).ok && /no emitters/.test(wornOnABody({ groups: [{ emitters: [] }] }).why), 'an effect with no emitters at all cannot be worn');

// --- the same rule against the client's own files ----------------------------------------------
// Additive: the pack is the owner's and is not in the repository, so its absence is not a failure.
const packDir = new URL('../../../assets-private/weapons/', import.meta.url);
const manifestFile = new URL('manifest.json', packDir);
if (existsSync(manifestFile)) {
  const manifest = JSON.parse(readFileSync(manifestFile, 'utf8')) as { effects?: Record<string, string> };
  const defOf = (file: string) => JSON.parse(readFileSync(new URL(file, packDir), 'utf8'));
  let judged = 0;
  for (const entry of EXTRA_EFFECTS as { name: string; worn?: boolean }[]) {
    const file = manifest.effects?.[entry.name];
    if (!file || !existsSync(new URL(file, packDir))) continue;
    const verdict = wornOnABody(defOf(file));
    if (entry.worn) {
      ok(verdict.ok, `the pack's own '${entry.name}', which the game hangs on a body, really can be worn by one`);
      judged++;
    } else console.log(`note ${entry.name}: ${verdict.ok ? 'could be worn by a body' : `could not be worn by a body — ${verdict.why}`}`);
  }
  if (!judged) console.log("note the pack carries no body-worn effect yet, so the rule was checked against fixtures alone (rerun the weapons command)");
} else console.log('note no converted weapons pack here, so the rule was checked against fixtures alone');

// --- the converter's list -----------------------------------------------------------------------
const names = (EXTRA_EFFECTS as { name: string }[]).map((e) => e.name);
ok(names.includes(FIRE_EFFECT), "the converter's list carries the burn under the name the game asks for");
ok(new Set(names).size === names.length, 'no name is on the list twice');
ok(new Set(EXTRA_EFFECTS.map((e: { path: string }) => e.path)).size === names.length, 'no file is on the list twice under two names');
ok(!!extraEffect(FIRE_EFFECT)?.worn, 'the burn is marked as one a body wears, which is what makes the converter check it');
ok(!extraEffect('nothing_of_the_sort'), 'an unknown name is not on the list');

// What a pack has not got, built from the list itself rather than by naming its entries here: a
// pack carrying everything but the burn is missing the burn and nothing else.
const allButBurn = Object.fromEntries(names.filter((n) => n !== FIRE_EFFECT).map((n) => [n, 'x']));
ok(missingExtraEffects(allButBurn).join() === FIRE_EFFECT, 'a pack converted before this wave is missing the burn and nothing else');
ok(missingExtraEffects(undefined).length === EXTRA_EFFECTS.length, 'a pack with no effects block at all is missing every one');
ok(missingExtraEffects(Object.fromEntries(names.map((n) => [n, 'x']))).length === 0, 'a pack converted now is missing none');

// Status: a pack short of one must read differently from a complete pack, which is what counting
// the keys in the pack's own block could never do.
const short = extraEffectsStatus(allButBurn);
const whole = extraEffectsStatus(Object.fromEntries(names.map((n) => [n, 'x'])));
ok(short.line !== whole.line, 'a pack short of the burn and a complete pack do not say the same thing');
ok(short.have === whole.have - 1 && short.total === whole.total && whole.missing.length === 0, 'the count is of the whole list, not of what the pack happens to carry');
ok(short.line.includes(FIRE_EFFECT) && !whole.line.includes(FIRE_EFFECT), 'the short pack names what it has not got and the whole one names nothing');
ok(extraEffectsStatus(undefined).have === 0, 'a pack with no effects block at all carries none of them');

// The game's own list of the names it may ask for, read as text, so the two tables cannot drift.
const src = readFileSync(new URL('../../../src/player/weapons.ts', import.meta.url), 'utf8');
const union = /export type ExtraEffect =([^;]+);/.exec(src)?.[1] ?? '';
const asked = [...union.matchAll(/'([^']+)'/g)].map((m) => m[1]);
ok(asked.length === names.length && asked.every((n) => names.includes(n)), "the game asks for exactly the names the converter's list writes");

// --- the game's choice ---------------------------------------------------------------------------
const fresh = { effects: { flame: 'particles/flame.json', onfire: 'particles/burn.json' } };
const own = pickFireLook(fresh);
ok(own?.file === 'particles/burn.json', "the client's own burn is drawn from where the pack has it");
ok(Number.isFinite(own?.lift), 'the lift is always a number, so what places it can add it without asking');

// A pack converted before the burn. It still carries the flame thrower and its fireball, and
// neither may be taken for a fire a body can wear — that is the blocker this file exists to pin.
const old = {
  effects: { flame: 'particles/flame.json', lightning: 'particles/lightning.json', lightningMuzzle: 'particles/muzzle.json', acid: 'particles/acid.json', ice: 'particles/ice.json' },
  weapons: [{ id: 'rifle_flame_thrower', fx: { id: 'bolt', index: 21, shot: 'particles/fireball.json' } }],
};
ok(pickFireLook(old) === null, 'a pack with no burn draws no fire, rather than standing the flame thrower\'s own fire in for one');
ok(pickFireLook({ effects: {} }) === null && pickFireLook(null) === null && pickFireLook(undefined) === null, 'no effects block, and no pack at all, draw nothing');

// The two lines the console can be told: they differ, the one that draws names what it draws, and
// the one that does not says what to run.
const lines = [fireLookLine(own), fireLookLine(null)];
ok(lines[0] !== lines[1], 'drawing the burn and drawing nothing say different things');
ok(lines[0].includes('particles/burn.json'), 'the line names the file being drawn');
ok(/weapons command/.test(lines[1]) && !/weapons command/.test(lines[0]), 'only the one that is not the real thing says what to rerun');

console.log(`${checks} checks passed`);
