/**
 * What a body that has been set alight is drawn with, chosen out of the weapons pack alone.
 *
 * The client has its own on-fire effect and the converter now writes it into the pack under the name
 * `onfire` (`EXTRA_EFFECTS` in `tools/swg/weapons.mjs`). A pack converted before that has not got it,
 * and there is nothing else in the pack to put in its place: a fire worn by a body has to meet two
 * conditions that nothing else the pack carries meets, and the conditions are the particle engine's
 * own arithmetic rather than anyone's taste.
 *
 *  - **It must draw on a body that is standing still.** An emitter whose particles are generated by
 *    distance draws a count taken from how far it moved since the last frame
 *    (`EmitterState.createNewParticles`), which on something standing still is nought, for ever. Only
 *    a rate-generated emitter, or a one-shot one, puts out anything on a body at rest.
 *  - **It must ride the body.** A local-space emitter keeps its particles in its own frame and puts
 *    them into the world only as they are drawn (`Emitter.spawn`), so they travel with whatever the
 *    effect is hung on. A world-space one leaves every particle where it was born, so a walking body
 *    lays a trail behind it and wears no flame at all.
 *
 * Every fire the pack carries beyond the burn fails one or both: the flame thrower's beam is
 * rate-generated but world-space and leaves at 10 m/s (on a body it is a 20-metre pillar), and the
 * fireball its weapon row fires is both distance-generated and world-space, so on a standing body it
 * draws nothing whatsoever and on a walking one it trails. So there is no stand-in, and a pack
 * converted before the burn draws no fire at all and says so, once, in the console. The rule itself
 * is `wornOnABody` in `tools/swg/weapons.mjs`, where the converter checks it against the very file it
 * ships on every run.
 *
 * Nothing is imported here on purpose: the rule is pure, so a node test can hand it a fixture
 * manifest without dragging three, the loaders or a display file in behind it.
 */

/** The pack's name for the client's own burn. */
export const FIRE_EFFECT = 'onfire';

/**
 * How far above the body's feet the fire is placed, in metres. The client's own burn is authored
 * 1.5 m up from wherever it is put (it was made for a standing person), so nothing is added here and
 * the handle goes at the feet. It is carried as a number rather than assumed, so that a lift per
 * body size — a burning bantha wears its flames at a standing person's chest — has one place to go.
 */
export const FIRE_LIFT = 0;

/** As much of the weapons manifest as the choice reads. */
export interface FireLookPack {
  effects?: Partial<Record<string, string>> | null;
}

export interface FireLook {
  /** The effect file, as the pack names it (relative to the weapons folder). */
  file: string;
  /** Metres to lift the effect above the body's feet; the client's own lifts itself inside the file. */
  lift: number;
}

/**
 * The fire to draw on a burning body, or null when the pack was converted before the burn — which
 * draws nothing, exactly as every pack did before this, rather than drawing a fire that would either
 * stand invisible or trail behind the body.
 */
export function pickFireLook(pack: FireLookPack | null | undefined): FireLook | null {
  const own = pack?.effects?.[FIRE_EFFECT];
  return own ? { file: own, lift: FIRE_LIFT } : null;
}

/** The one line the console is told, so it is plain what a session is drawing and why. */
export function fireLookLine(look: FireLook | null): string {
  if (look) return `fire: the client's own burn (${look.file})`;
  return 'fire: this weapons pack was converted before the burn, and nothing else in it can stand in for one (every other fire it carries either draws nothing at all on a body standing still or leaves its flames behind as the body walks), so a burning body is drawn with no fire until the weapons command is run again';
}
